prompts:
  image_prompt: |
    Generate an AI-crafted image description in English (50-300 chars NOT MORE):
    THEME: Beautiful but clearly artificial
    SETTING: Unreal environment
    MAIN ELEMENT: One striking feature
    MOTION: Suggests subtle movement
    STYLE: Different art style each time
    MOOD: Inspiring, surreal
    PURPOSE: Base frame for background video
    FORMAT: "An [environment] where [main element] appears to [motion]. Hyper-detailed, beautifully artificial, and captivating."

  video_prompt: |
    Generate an AI-styled video description in English (50-300 chars NOT MORE) based on:
    SCENE: {scene}
    VISUAL: Rich, AI-generated
    MOTION: Layered (slow background + continuous main element)
    FOCUS: Background dominates, motion adds depth
    MOOD: Surreal, elegant
    PURPOSE: Loopable dynamic backdrop
    STYLE: Different each time
    FORMAT: "[Unreal, richly detailed environment]. [Layered motion: subtle background flow + continuous main element movement]. Feels immersive and beautifully artificial."

  title_prompt: |
    Write one short impactful title in English (1-3 words).
    FORMAT: "title"

  description_prompt: |
    Write a 50-character YouTube description for:
    VIDEO: {title}
    RULES:
    1. Start with a random relevant emoji
    2. Mention AI-generated visual
    3. Hint at message
    4. Exactly 50 characters
    FORMAT: "[Emoji] [Visual hint] | [Message tease]..."

  video_text_prompt: |
    Write ONE motivational quote in English (2-6 sentences) about ambition and individuality.
    FORMAT: "quote"

tags: ["motivational", "motivation", "business", "money", "cars", "flex", "beautiful", "surreal", "background", "epic"]
