prompts:
  image_prompt: |
    Generate an AI-crafted image description in English (50-300 chars NOT MORE):
    THEME: Normal situation with impending absurdity
    SETTING: Ordinary location with subtle unease
    MAIN ELEMENT: Random person performing mundane activity
    DETAIL: Visual hint of approaching bizarre disaster
    STYLE: Hyper-realistic or cinematic
    MOOD: Tense, unsettling
    PURPOSE: Setup for shocking viral video
    FORMAT: "A [person] [action] in [location]. Hyper-realistic yet unnerving. Style: [style]."

  video_prompt: |
    Generate an AI-styled video description in English (50-300 chars NOT MORE) based on:
    SCENE: {scene}
    ACTION: Sudden absurd catastrophe
    VISUAL: Shockingly bizarre, meme-worthy
    MOTION: Chaotic, rapid cuts
    FOCUS: Victim's extreme reaction
    MOOD: Viral, wtf moment
    PURPOSE: Clickbait shock content
    STYLE: Different each time
    FORMAT: "[Normal location] turns chaotic as [absurd disaster occurs]. Jaw-dropping reactions captured in [style]."

  title_prompt: |
    Write one short shocking title in English (1-3 words).
    FORMAT: "title"

  description_prompt: |
    Write a 50-character YouTube description for:
    VIDEO: {title}
    RULES:
    1. Start with a random relevant emoji
    2. Mention AI-generated visual
    3. Hint at shocking content
    4. Exactly 50 characters
    FORMAT: "[Emoji] AI-generated shock | [Tease incident]..."

  video_text_prompt: |
    Write ONE shocking caption in English (1-2 sentences) about the incident.
    FORMAT: "[Dramatic statement about the event]. [Shocking conclusion]."

tags: ["news","viral", "shocking", "absurd", "wtf", "meme", "trending", "reaction", "unexpected", "chaos", "disaster"]